#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <trackingLib/math/linalg/matrix.h>
#include <sstream>
#include <string>


#define STRINGIFY(x) #x
#define MACRO_STRINGIFY(x) STRINGIFY(x)

namespace py = pybind11;

// this function has to be autogenerated in Python given the max allowed dimension
template <typename FloatType, std::size_t Rows, std::size_t Cols>
void declare_matrix(py::module& m, const std::string& typestr)
{
  using MT                 = tracking::math::Matrix<FloatType, Rows, Cols>;
  std::string pyclass_name = std::string("Matrix") + typestr + std::to_string(Rows) + std::to_string(Cols);
  // clang-format off
  py::class_<MT>(m, pyclass_name.c_str(), py::buffer_protocol(), py::dynamic_attr())
    .def(py::init<>())
    .def(py::init<const std::array<typename MT::value_type, MT::Rows * MT::Cols>&>())
    .def("__add__", [](MT& mat, const MT& other) { return mat.operator+=(other); })
    .def("__sub__", [](MT& mat, const MT& other) { return mat.operator-=(other); })
    .def("__mul__", [](MT& mat, const typename MT::value_type scalar) { return mat.operator*=(scalar); })
    .def("__div__", [](MT& mat, const typename MT::value_type scalar) { return mat.operator/=(scalar); })
    .def("__mul__", [](MT& mat, const tracking::math::Matrix<typename MT::value_type, MT::Cols, 1>& other) { return mat.operator*(other); })
    .def("__mul__", [](MT& mat, const tracking::math::Matrix<typename MT::value_type, MT::Cols, 2>& other) { return mat.operator*(other); })
    .def("__repr__", [](const MT& mat) {
      std::stringstream stream;
      stream << mat.print();
      return stream.str(); 
    });
  // clang-format on
}

PYBIND11_MODULE(pytracking, m)
{
#if 0
dims  = list(range(1, 4))
for rows in dims:
    for cols in dims:
        print(f'declare_matrix<float, {rows}, {cols}>(m, "F");')
        print(f'declare_matrix<double, {rows}, {cols}>(m, "D");')
#endif

  declare_matrix<float, 1, 1>(m, "F");
  declare_matrix<double, 1, 1>(m, "D");
  declare_matrix<float, 1, 2>(m, "F");
  declare_matrix<double, 1, 2>(m, "D");
  declare_matrix<float, 1, 3>(m, "F");
  declare_matrix<double, 1, 3>(m, "D");
  declare_matrix<float, 2, 1>(m, "F");
  declare_matrix<double, 2, 1>(m, "D");
  declare_matrix<float, 2, 2>(m, "F");
  declare_matrix<double, 2, 2>(m, "D");
  declare_matrix<float, 2, 3>(m, "F");
  declare_matrix<double, 2, 3>(m, "D");
  declare_matrix<float, 3, 1>(m, "F");
  declare_matrix<double, 3, 1>(m, "D");
  declare_matrix<float, 3, 2>(m, "F");
  declare_matrix<double, 3, 2>(m, "D");
  declare_matrix<float, 3, 3>(m, "F");
  declare_matrix<double, 3, 3>(m, "D");
#ifdef VERSION_INFO
  m.attr("__version__") = MACRO_STRINGIFY(VERSION_INFO);
#else
  m.attr("__version__") = "dev";
#endif
}
