name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-self-contained-headers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake doxygen graphviz lcov

    - name: Configure with CMake
      run: cmake -S . -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Debug -DBUILD_HEADER_TESTS=ON

    - name: Build header tests with CMake
      run: cmake --build build --target header_tests
    
    - name: Run header tests
      run: ctest --test-dir build -R "header_test_" --output-on-failure

  verify-class-contracts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake doxygen graphviz lcov

    - name: Configure with CMake
      run: cmake -S . -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Debug

    - name: Build with CMake
      run: cmake --build build

  doxygen-gen:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake doxygen graphviz lcov

    - name: Build doxgen doc
      run: doxygen .

  coverage-gen:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake doxygen graphviz lcov

    - name: Build coverage report
      run: ./report_coverage.sh

  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [g++, clang++]
        cxx_standard: [17, 20]
        build_type: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake doxygen graphviz lcov

    - name: Configure with CMake
      run: cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build with CMake
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build --output-on-failure

#  build-and-test-windows:
#    runs-on: windows-latest
#
#    strategy:
#      matrix:
#        compiler: [cl]
#        cxx_standard: [17] #, 20]
#        build_type: [Debug] #, Release]
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Configure with CMake
#      run: cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
#
#    - name: Build with CMake
#      run: cmake --build build
#
#    - name: Run tests
#      run: ctest --test-dir build --output-on-failure